/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'Quick_Start',
    {
      type: 'category',
      label: 'Advanced Topics',
      link: {
        type: 'generated-index',
        title: 'Advanced Topics',
        description: 'Implementation guides and deeper SDK behavior notes.',
      },
      items: [{type: 'autogenerated', dirName: 'Advanced_Topics'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'API_Reference/index',
      },
      items: [
        'API_Reference/Generated/index',
        {
          type: 'category',
          label: 'Browser API',
          link: {
            type: 'doc',
            id: 'API_Reference/Generated/browser/index',
          },
          items: [{type: 'autogenerated', dirName: 'API_Reference/Generated/browser'}],
        },
        {
          type: 'category',
          label: 'Node API',
          link: {
            type: 'doc',
            id: 'API_Reference/Generated/node/index',
          },
          items: [{type: 'autogenerated', dirName: 'API_Reference/Generated/node'}],
        },
        {
          type: 'category',
          label: 'Legacy API Pages',
          collapsed: true,
          items: [
            'API_Reference/cdcamera',
            'API_Reference/cddecoder',
            'API_Reference/cddevice',
            'API_Reference/cdlicense',
            'API_Reference/cdperformancefeatures',
            'API_Reference/cdresult',
            {
              type: 'category',
              label: 'CDSymbology',
              link: {
                type: 'doc',
                id: 'API_Reference/CDSymbology/index',
              },
              items: [{type: 'autogenerated', dirName: 'API_Reference/CDSymbology'}],
            },
          ],
        },
      ],
    },
    'Release_Notes',
  ],
};

module.exports = sidebars;
